### ISSUE TITLE
Code section render fail

### ISSUE THREAD

**Issue by lettucebo** [aspnet/AspNetCore.Docs.zh-tw#104]
I found out that this page all code section with highlight render fail, although copy function still work fine

I use the private view to ensure no extension effect, still get the same result

![Annotation 2019-07-08 145631](https://user-images.githubusercontent.com/891383/60789107-d3a9e480-a190-11e9-9af3-a962b5333357.png)
![Annotation 2019-07-08 145622](https://user-images.githubusercontent.com/891383/60789108-d3a9e480-a190-11e9-8748-75726da8890e.png)
![Annotation 2019-07-08 145643](https://user-images.githubusercontent.com/891383/60789109-d3a9e480-a190-11e9-86d3-6d1ccba04ee1.png)

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [快取在記憶體中的 ASP.NET Core](https://docs.microsoft.com/zh-tw/aspnet/core/performance/caching/memory?view=aspnetcore-2.2)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/aspnet/AspNetCore.Docs.zh-tw/blob/live/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I'm sorry for the inconvenience. This is a system wide problem that's tracked in https://github.com/aspnet/AspNetCore.Docs/issues/13143.

**Comment by Rick-Anderson** [comment]
Please close this issue.

**Comment by lettucebo** [comment]
ref [aspnet/AspNetCore.Docs#13143](https://github.com/aspnet/AspNetCore.Docs/issues/13143)
Close issue
