### ISSUE TITLE
Some translation error in the "How to identify the SignalR version" section

### ISSUE THREAD

**Issue by SoonYang** [aspnet/AspNetCore.Docs.zh-tw#130]
These should not be translated in zh-TW since they are packages names:
- How to identify the SignalR version

1. Server NuGet package

| en-US | Current | Should be like |
| -------- | -------- | -------- |
| Microsoft.AspNet.SignalR | SignalR | Microsoft.AspNet.SignalR |

2. Client NuGet packages

| en-US | Current | Should be like |
| -------- | -------- | -------- |
| Microsoft.AspNet.SignalR.Client<br/>Microsoft.AspNet.SignalR.JS | SignalR。台<br/>SignalR。NODE.JS | Microsoft.AspNet.SignalR.Client<br/>Microsoft.AspNet.SignalR.JS |
| Microsoft.AspNetCore.SignalR.Client | AspNetCore.SignalR。台 | Microsoft.AspNetCore.SignalR.Client|

thanks

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 04f4bdfd-dfac-d6ae-4bd9-57439d300a5d
* Version Independent ID: 1f37f1ba-3e43-e726-f231-52acc6d26516
* Content: [SignalR 和 ASP.NET Core 之間的差異 SignalR](https://docs.microsoft.com/zh-tw/aspnet/core/signalr/version-differences?view=aspnetcore-3.1)
* Content Source: [aspnetcore/signalr/version-differences.md](https://github.com/aspnet/AspNetCore.Docs.zh-tw/blob/live/aspnetcore/signalr/version-differences.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by srvbpigh** [comment]
Hello, @SoonYang
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
您好，@SoonYang，   

謝謝您的寶貴意見。  

我們的編審小組審閱了您提出的語言建議，並接受了這些建議。我們已實作您的意見反應並發佈至 Docs 網站上已更新文章的以下頁面 https://docs.microsoft.com/zh-tw/aspnet/core/signalr/version-differences?view=aspnetcore-3.1。   

我們由衷感謝您對文章的貢獻，並期望您繼續提供寶貴的意見。  

順頌時祺  
Microsoft DOCS 國際小組
