### ISSUE TITLE
優化資料存取章節 文案有誤

### ISSUE THREAD

**Issue by derek82511** [aspnet/AspNetCore.Docs.zh-tw#131]
在存取資料進行唯讀時，**請不要在** Entity Framework Core 中使用無追蹤查詢。 EF Core 可以更有效率地傳回無追蹤查詢的結果。
應為：
在存取資料進行唯讀時，**請在** Entity Framework Core 中使用無追蹤查詢。 EF Core 可以更有效率地傳回無追蹤查詢的結果。

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 9599d917-4e43-f1ae-452a-1f11aaa985ed
* Version Independent ID: 5cc05b6c-c671-3607-3217-7db73ebc1f28
* Content: [ASP.NET Core 效能最佳做法](https://docs.microsoft.com/zh-tw/aspnet/core/performance/performance-best-practices?view=aspnetcore-3.1)
* Content Source: [aspnetcore/performance/performance-best-practices.md](https://github.com/aspnet/AspNetCore.Docs.zh-tw/blob/live/aspnetcore/performance/performance-best-practices.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @derek82511
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
您好，@derek82511，   

謝謝您的寶貴意見。  

我們的編審小組審閱了您提出的語言建議，並接受了這些建議。我們已實作您的意見反應並發佈至 Docs 網站上已更新文章的以下頁面 https://docs.microsoft.com/zh-tw/aspnet/core/performance/performance-best-practices?view=aspnetcore-3.1。   

我們由衷感謝您對文章的貢獻，並期望您繼續提供寶貴的意見。  

順頌時祺  
Microsoft DOCS 國際小組
