### ISSUE TITLE
{2>名稱<2} ?

### ISSUE THREAD

**Issue by doggy8088** [aspnet/AspNetCore.Docs.zh-tw#134]
What is this `{2&gt;名稱&lt;2}` in this doc?

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: fa4c23ba-19f6-d847-fefa-a61e283d5fde
* Version Independent ID: e7df465a-5f3b-1522-b2d9-5e3afbf74257
* Content: [ASP.NET Core 的部分標記協助程式](https://docs.microsoft.com/zh-tw/aspnet/core/mvc/views/tag-helpers/built-in/partial-tag-helper?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/partial-tag-helper.md](https://github.com/aspnet/AspNetCore.Docs.zh-tw/blob/live/aspnetcore/mvc/views/tag-helpers/built-in/partial-tag-helper.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by srvbpigh** [comment]
Hello, @doggy8088
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
謝謝您的寶貴意見。  

我們的工程小組審閱了您提出的建議，並接受了這些建議。我們已實作您的意見反應並發佈至 Docs 網站上已更新文章的以下頁面 https://docs.microsoft.com/zh-tw/aspnet/core/mvc/views/tag-helpers/built-in/partial-tag-helper?view=aspnetcore-3.1。   

我們由衷感謝您對文章的貢獻，並期望您繼續提供寶貴的意見。  

順頌時祺  
Microsoft DOCS 國際小組
