### ISSUE TITLE
Suggestion: change the page title

### ISSUE THREAD

**Issue by doggy8088** [aspnet/AspNetCore.Docs.zh-tw#135]
Current: `3.0 ASP.NET Core 的新功能`

Suggestion: `ASP.NET Core 3.0 的新功能`

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 2a3ff3cd-e7c3-f5f8-8993-067ca43f4ccc
* Version Independent ID: 8b8283b5-10f0-139d-b069-6ffab0ea4ca1
* Content: [3\.0 ASP.NET Core 的新功能](https://docs.microsoft.com/zh-tw/aspnet/core/release-notes/aspnetcore-3.0?view=aspnetcore-3.1)
* Content Source: [aspnetcore/release-notes/aspnetcore-3.0.md](https://github.com/aspnet/AspNetCore.Docs.zh-tw/blob/live/aspnetcore/release-notes/aspnetcore-3.0.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @doggy8088
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
this looks like a pure translation issue.
 的新功能  -> New features

**Comment by srvbpigh** [comment]
Hello, @doggy8088,  

Thank you for your feedback. 

Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-tw/aspnet/core/release-notes/aspnetcore-3.0?view=aspnetcore-3.1.  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 
Microsoft DOCS International Team
