### ISSUE TITLE
"ASP.NET Core 中的 JsonPatch" is not in sync with English version

### ISSUE THREAD

**Issue by doggy8088** [aspnet/AspNetCore.Docs.zh-tw#137]
"ASP.NET Core 中的 JsonPatch" is not in sync with English version

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 593f528c-61b9-7021-335d-c1c0ec1814d1
* Version Independent ID: 6a88d237-1a03-b865-e3c5-20ceedef2a1f
* Content: [ASP.NET Core Web API 中的 JsonPatch](https://docs.microsoft.com/zh-tw/aspnet/core/web-api/jsonpatch?view=aspnetcore-3.1#jsonpatch-in-aspnet-core)
* Content Source: [aspnetcore/web-api/jsonpatch.md](https://github.com/aspnet/AspNetCore.Docs.zh-tw/blob/live/aspnetcore/web-api/jsonpatch.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by srvbpigh** [comment]
Hello, @doggy8088
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @doggy8088 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by doggy8088** [comment]
The Chinese translation:

```txt
Microsoft.AspNetCore.JsonPatch (英文) NuGet 套件中會提供 JSON Patch 的 ASP.NET Core 實作。 此套件隨附於 Microsoft.AspnetCore.App 中繼套件中。
```

The English original:

```txt
The ASP.NET Core implementation of JSON Patch is provided in the Microsoft.AspNetCore.JsonPatch NuGet package.
```

This part should be removed:

```txt
 此套件隨附於 Microsoft.AspnetCore.App 中繼套件中。
```

It because the `Microsoft.AspNetCore.JsonPatch` is not part of `Microsoft.AspnetCore.App` anymore.

**Comment by ticianaciminari** [comment]
Thank you for your feedback. 

Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-tw/aspnet/core/web-api/jsonpatch?view=aspnetcore-3.1#jsonpatch-in-aspnet-core.  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 

Microsoft DOCS International Team
