### ISSUE TITLE
Suggestion: change the page title

### ISSUE THREAD

**Issue by doggy8088** [aspnet/AspNetCore.Docs.zh-tw#139]
Current: `3.1 ASP.NET Core 的新功能`

Suggestion: `ASP.NET Core 3.1 的新功能`

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 099645fa-864f-d949-4581-f1ab276b526e
* Version Independent ID: 264988a9-ba66-012d-8609-760bc736746c
* Content: [3\.1 ASP.NET Core 的新功能](https://docs.microsoft.com/zh-tw/aspnet/core/release-notes/aspnetcore-3.1?view=aspnetcore-3.1)
* Content Source: [aspnetcore/release-notes/aspnetcore-3.1.md](https://github.com/aspnet/AspNetCore.Docs.zh-tw/blob/live/aspnetcore/release-notes/aspnetcore-3.1.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @doggy8088
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
您好，@doggy8088，   

謝謝您的寶貴意見。  

我們的編審小組審閱了您提出的語言建議，並接受了這些建議。我們已實作您的意見反應並發佈至 Docs 網站上已更新文章的以下頁面 https://docs.microsoft.com/zh-tw/aspnet/core/release-notes/aspnetcore-3.1?view=aspnetcore-3.1。   

我們由衷感謝您對文章的貢獻，並期望您繼續提供寶貴的意見。  

順頌時祺  
Microsoft DOCS 國際小組
